[project]
name = "mechdriver"
version = "2025.10.0"
description = "Automated workflow routines for calculating theoretical data for reaction mechanisms"
readme = "README.md"
dependencies = ["hyperqueue"]
requires-python = ">= 3.11"

[project.scripts]
automech = 'mechdriver.cli:main'

[dependency-groups]
test = ["pytest", "pytest-xdist[psutil]"]
lint = ["ruff", "mypy", "pre-commit"]
docs = ["sphinx", "myst-parser", "sphinx-book-theme", "sphinx-autodoc-typehints"]
new_arch = ["hyperqueue>=0.24.0"]
dev = ["jupytext"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

# Hatchling configurations
[tool.hatch.build.targets.sdist]
only-include = ["src/mechdriver", "src/drivers", "src/mechlib", "src/mechroutines"]
sources = { "src" = "" }

[tool.hatch.build.targets.wheel]
only-include = ["src/mechdriver", "src/drivers", "src/mechlib", "src/mechroutines"]
sources = { "src" = "" }

# Pixi configurations
[tool.pixi.workspace]
channels = ["conda-forge", "Auto-Mech"]
platforms = ["linux-64"]
preview = ["pixi-build"]

#   - Build
[tool.pixi.package]
name = "mechdriver"

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[tool.pixi.package.host-dependencies]
hatchling = "==1.26.3"

[tool.pixi.package.run-dependencies]
pydantic = "*"
pac99 = "*"
projrot = "*"
thermp = "*"
mess-static = "*"
autochem = { path = "src/_autochem" }
autoio = { path = "src/_autoio" }
autofile = { path = "src/_autofile" }
mechanalyzer = { path = "src/_mechanalyzer" }

#   - Development environments
[tool.pixi.pypi-dependencies]
mechdriver = { path = ".", editable = true }
autochem = { path = "src/_autochem", editable = true }
autoio = { path = "src/_autoio", editable = true }
autofile = { path = "src/_autofile", editable = true }
mechanalyzer = { path = "src/_mechanalyzer", editable = true }

[tool.pixi.dependencies]
pydantic = "*"
pac99 = "*"
projrot = "*"
thermp = "*"
mess-static = "*"

[tool.pixi.feature.build.dependencies]
rattler-build = ">=0.47.1"

[tool.pixi.feature.dev.dependencies]
gh = "*"

[tool.pixi.system-requirements]
linux = "3.10"
libc = { family="glibc", version="2.17" }

[tool.pixi.feature.new_arch.system-requirements]
linux = "3.10"  # Newer architecture required for current HyperQueue version
libc = { family="glibc", version="2.28" }

[tool.pixi.environments]
test = ["test"]
test2 = ["test", "new_arch"]
lint = ["lint"]
docs = ["docs"]
build = ["build"]
dev = ["test", "lint", "docs", "build", "dev"]
dev2 = ["test", "lint", "docs", "build", "dev", "new_arch"]

#   - Tasks
[tool.pixi.tasks]
extra-dev-installs = { cmd = "./scripts/extra-dev-installs.sh", cwd = "." }
subrepo-push = { cmd = "./scripts/subrepo-push.sh", cwd = "." }
status = { cmd = "./scripts/status.sh", cwd = "." }
node = { cmd = "./scripts/node.sh" }
test = { cmd = "./scripts/test.py" }

[tool.pixi.feature.dev.tasks]
gh-auth = { cmd = "gh auth login -s workflow", cwd = "." }
subrepo-pull = { cmd = "./scripts/subrepo-pull.sh", cwd = "." }
vis = { cmd = "./scripts/vis.sh" }

# Ruff configurations
[tool.ruff]
target-version = "py311"
extend-select = [
    "E",      # style errors
    "F",      # flakes
    "D",      # pydocstyle
    "I001",   # isort
    "UP",     # pyupgrade
    "N",      # pep8-naming
    "C",      # flake8-comprehensions
    "B",      # flake8-bugbear
    "A001",   # flake8-builtins
    "RUF",    # ruff-specific rules
    "RUF100", # Unused noqa directive
]
extend-ignore = [
    "RUF022", # Require __all__ to be sorted
]
